language: python
python:
  - "3.11"

services:
  - docker

env:
  global:
    - IMAGE_NAME=master
    - DOCKER_REPO=aradgonen98/zenity-devops-challenge

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

install:
  - cd python-app
  - pip install -r requirements.txt

script:
  - python test_app.py
  - docker build -t $IMAGE_NAME .

deploy:
  provider: script
  script:
    - docker tag $IMAGE_NAME $DOCKER_REPO:latest
    - docker push $DOCKER_REPO:latest
  on:
    branch: master